# Generated by Django 4.2.4 on 2023-08-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
