# Generated by Django 4.2.4 on 2023-08-16 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender_by',
        ),
        migrations.AddField(
            model_name='notification',
            name='send_by',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='sendBy', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
